Repository BTS-Busan-Trip-Supporter/front-end, pull requests merged in 2024-09, with the labels that each got.

#45 feat: Apply changed design to travel-auto page
  public/button/check.svg
  public/button/like.png
  public/button/plus.svg
  public/button/unlike.png
  public/check-non.svg
  public/check.svg
  src/app/pages/travel-auto-page.tsx
  src/components/DropBox.tsx
  src/components/LoadingCard.tsx
  src/components/RecentSearch.tsx
  src/components/ScrollMotion.tsx
  src/components/SearchBox.tsx
  src/components/index.ts
  src/components/travel/DetailCard.tsx
  src/components/travel/Loading.tsx
  src/components/travel/ReviewCard.tsx
  src/components/travel/index.ts
Labels: Feature, UI/UX

#46 feat: add tour-spot, trip api
  src/features/tour-spot/index.ts
  src/features/tour-spot/tour-spot.api.ts
  src/features/tour-spot/tour-spot.dto.ts
  src/features/tour-spot/tour-spot.hook.ts
  src/features/trip/index.ts
  src/features/trip/trip.api.ts
  src/features/trip/trip.dto.ts
  src/features/trip/trip.hook.ts
  src/features/trip/trip.type.ts
Labels: Feature, API

#47 feat: Added auth API
  next.config.mjs
  package-lock.json
  package.json
  public/kakao.svg
  public/kakaotalk.png
  public/user-active.svg
  public/user.svg
  src/__test__/NavigationBar.test.tsx
  src/app/layout.tsx
  src/app/login/email/page.tsx
  src/app/page.tsx
  src/app/pages/email-login-page.tsx
  src/app/pages/index.ts
  src/app/pages/login-page.tsx
  src/app/pages/my-page.tsx
  src/app/pages/profile-edit-page.tsx
  src/app/pages/sign-up-page.tsx
  src/app/pages/travel-page.tsx
  src/app/sign-up/page.tsx
  src/app/travel/page.tsx
  src/components/InputField.tsx
  src/components/NavigationBar.tsx
  src/components/index.ts
  src/components/profile/EditPasswordSection.tsx
  src/components/profile/EditProfileSection.tsx
  src/components/profile/LogInForm.tsx
  src/components/profile/SignUpForm.tsx
  src/components/profile/index.ts
  src/features/member/index.ts
  src/features/member/member.api.ts
  src/features/member/member.dto.ts
  src/features/member/member.hook.ts
  src/features/member/member.type.ts
  src/features/profile/index.ts
  src/features/profile/profile.type.ts
  src/features/toast/index.ts
  src/features/toast/toast.hook.ts
  src/features/toast/toast.slice.ts
  src/features/toast/toast.type.ts
  src/providers/AuthProvider.tsx
  src/providers/ToastProvider.tsx
  src/providers/index.ts
Labels: Feature, API, UI/UX

#48 fix: add missing export in index files
  src/features/tour-spot/index.ts
  src/features/trip/index.ts
Labels: API, Fix

#50 feat: Applied travel-auto-mode API and review API
  public/button/like.png
  public/button/unlike.png
  public/gray-pin.svg
  src/app/pages/index.ts
  src/app/pages/my-page.tsx
  src/app/pages/record-list-page.tsx
  src/app/pages/record-review-page.tsx
  src/app/pages/travel-auto-page.tsx
  src/app/pages/travel-page.tsx
  src/app/record/[id]/page.tsx
  src/app/record/page.tsx
  src/components/DropBox.tsx
  src/components/LoadingCard.tsx
  src/components/NavigationBar.tsx
  src/components/SearchBox.tsx
  src/components/TravelList.tsx
  src/components/TravelLog.tsx
  src/components/index.ts
  src/components/profile/SignUpForm.tsx
  src/components/travel/DetailCard.tsx
  src/components/travel/Loading.tsx
  src/components/travel/ReviewCard.tsx
  src/components/travel/traveler/TravelerTravelReview.tsx
  src/features/travel-schedule/travel-schedule.model.ts
  src/features/trip/index.ts
  src/features/trip/trip.api.ts
  src/features/trip/trip.dto.ts
  src/features/trip/trip.hook.ts
  src/features/trip/trip.type.ts
  src/features/trip/trip.util.ts
  src/providers/AuthProvider.tsx
  src/shared/convert-dates.ts
  src/shared/index.ts
Labels: Feature, API

#51 fix: resize navigationbar
  src/app/globals.css
  src/app/layout.tsx
  src/components/NavigationBar.tsx
  src/components/travel/ContentsCard.tsx
Labels: UI/UX

#52 feat: apply design, apis changes
  eslint.config.mjs
  public/search.svg
  src/__test__/travel-schedule-actions.test.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/pages/my-page.tsx
  src/app/pages/travel-auto-page.tsx
  src/app/pages/travel-page.tsx
  src/app/pages/travel-traveler-page.tsx
  src/components/Calendar.tsx
  src/components/CustomButton.tsx
  src/components/NavigationBar.tsx
  src/components/SearchBox.tsx
  src/components/TimeCard.tsx
  src/components/TravelComponent.tsx
  src/components/TravelLog.tsx
  src/components/travel/ContentsCard.tsx
  src/components/travel/DetailCard.tsx
  src/components/travel/PurpleBackground.tsx
  src/components/travel/traveler/TravelerActivityRecommendation.tsx
  src/components/travel/traveler/TravelerActivitySelection.tsx
  src/components/travel/traveler/TravelerAddDays.tsx
  src/components/travel/traveler/TravelerLocationConfirm.tsx
  src/components/travel/traveler/TravelerLocationSearch.tsx
  src/components/travel/traveler/TravelerMain.tsx
  src/components/travel/traveler/TravelerScheduleConfirm.tsx
  src/components/travel/traveler/TravelerScheduleSelection.tsx
  src/components/travel/traveler/TravelerTimeSelection.tsx
  src/components/travel/traveler/TravelerTravelArrange.tsx
  src/components/travel/traveler/TravelerTravelReview.tsx
  src/components/travel/traveler/index.ts
  src/features/member/member.api.ts
  src/features/member/member.dto.ts
  src/features/toast/toast.slice.ts
  src/features/tour-spot/tour-spot.hook.ts
  src/features/travel-schedule/index.ts
  src/features/travel-schedule/travel-schedule.model.ts
  src/features/travel-schedule/travel-schedule.slice.ts
  src/features/travel-schedule/travel-schedule.type.ts
  src/features/trip/trip.hook.ts
  src/features/trip/trip.slice.ts
  src/features/trip/trip.type.ts
  src/providers/TravelScheduleStoreProvider.tsx
  src/providers/index.ts
  src/shared/useIntersectionObserver.ts
Labels: Feature, API, UI/UX

#53 fix: set default image if none
  public/no-image.svg
  src/components/LoadingCard.tsx
  src/components/travel/DetailCard.tsx
  src/features/tour-spot/tour-spot.api.ts
  src/features/trip/trip.api.ts
Labels: UI/UX, Fix

#54 fix: Fixed travel-auto page layout
  src/app/globals.css
  src/app/layout.tsx
  src/app/pages/travel-auto-page.tsx
  src/components/NavigationBar.tsx
  src/components/travel/ContentsCard.tsx
  src/components/travel/DetailCard.tsx
  src/components/travel/Loading.tsx
  src/components/travel/PurpleBackground.tsx
  src/providers/AuthProvider.tsx
Labels: UI/UX

#56 feat: add actions to remove item (tour, activity)
  src/components/travel/traveler/TravelerAddDays.tsx
  src/features/trip/trip.slice.ts
Labels: Feature, UI/UX

#55 fix: modify layout, add move to prev page action in traveler-mode
  src/app/pages/my-page.tsx
  src/app/pages/travel-traveler-page.tsx
  src/components/LoadingCard.tsx
  src/components/NavigationBar.tsx
  src/components/travel/ContentsCard.tsx
  src/components/travel/DetailCard.tsx
  src/components/travel/traveler/TravelerActivityRecommendation.tsx
  src/components/travel/traveler/TravelerActivitySelection.tsx
  src/components/travel/traveler/TravelerAddDays.tsx
  src/components/travel/traveler/TravelerLocationConfirm.tsx
  src/components/travel/traveler/TravelerLocationSearch.tsx
  src/components/travel/traveler/TravelerScheduleConfirm.tsx
  src/components/travel/traveler/TravelerScheduleSelection.tsx
  src/components/travel/traveler/TravelerTravelArrange.tsx
  src/features/trip/trip.slice.ts
Labels: Feature, UI/UX, Fix

#58 feat: Modified some logic
  src/app/pages/my-page.tsx
  src/app/pages/profile-edit-page.tsx
  src/app/pages/travel-auto-page.tsx
  src/app/pages/travel-page.tsx
  src/components/TravelLog.tsx
  src/components/profile/EditPasswordSection.tsx
  src/components/profile/EditProfileSection.tsx
  src/components/travel/DetailCard.tsx
  src/components/travel/Loading.tsx
  src/components/travel/traveler/TravelerActivityRecommendation.tsx
  src/features/member/member.api.ts
  src/features/member/member.hook.ts
  src/providers/AuthProvider.tsx
Labels: Fix

#59 feat: doneeeeeeeeeeeeee
  src/app/pages/travel-auto-page.tsx
  src/app/pages/travel-page.tsx
  src/app/pages/travel-traveler-page.tsx
  src/components/DropBox.tsx
  src/components/travel/DetailCard.tsx
  src/components/travel/Loading.tsx
  src/components/travel/traveler/TravelerActivityRecommendation.tsx
  src/components/travel/traveler/TravelerActivitySelection.tsx
  src/components/travel/traveler/TravelerAddDays.tsx
  src/components/travel/traveler/TravelerLocationSearch.tsx
  src/components/travel/traveler/TravelerScheduleConfirm.tsx
  src/components/travel/traveler/TravelerTravelArrange.tsx
  src/features/trip/trip.api.ts
  src/features/trip/trip.dto.ts
  src/features/trip/trip.slice.ts
  src/providers/AuthProvider.tsx
  src/providers/ToastProvider.tsx
Labels: Feature, API, UI/UX, Fix

#62 release: v1.0.1
  package-lock.json
  package.json
  src/app/favicon.ico
  src/app/pages/login-page.tsx
Labels: Deploy

#63 chore: Update deploy-to-aws-ec2.yml
  .github/workflows/deploy-to-aws-ec2.yml
Labels: Bug, Deploy

#64 feat: Applied feedback
  src/__test__/NavigationBar.test.tsx
  src/app/pages/travel-page.tsx
  src/components/NavigationBar.tsx
  src/components/SearchBox.tsx
  src/components/TravelLog.tsx
  src/components/profile/EditPasswordSection.tsx
  src/components/profile/EditProfileSection.tsx
  src/components/travel/traveler/TravelerActivitySelection.tsx
  src/components/travel/traveler/TravelerLocationSearch.tsx
  src/features/member/member.hook.ts
  src/providers/AuthProvider.tsx
Labels: API, UI/UX, Fix
