Repository BTS-Busan-Trip-Supporter/front-end, pull requests merged in 2024-08, with the labels that each got.

#9 chore: Modify Lint and Format Github actions
  .github/workflows/lint-format.yml
  package.json
Labels: feature

#8 feat: Add my-page and login-page layout
  public/background/bottom-login.svg
  public/background/bottom-travel.svg
  public/background/top-left-login.svg
  public/background/top-left-travel.svg
  public/background/top-right-login.svg
  public/background/top-right-travel.svg
  public/ellipsis.svg
  public/kakao.svg
  public/mail.png
  public/start-social-login.svg
  public/write-active.png
  public/write.png
  public/x.svg
  src/app/globals.css
  src/app/login/page.tsx
  src/app/my/page.tsx
  src/app/pages/index.ts
  src/app/pages/login-page.tsx
  src/app/pages/my-page.tsx
  src/components/Background.tsx
  src/components/Header.tsx
  src/components/index.ts
Labels: feature

#13 chore: Create run-test.yml
  .github/workflows/lint-format.yml
  .github/workflows/run-test.yml
  package.json
Labels: feature

#14 feat: Add travel-schedule slice
  .github/workflows/lint-format.yml
  .github/workflows/run-test.yml
  eslint.config.mjs
  package-lock.json
  package.json
  src/__test__/travel-schedule-actions.test.ts
  src/app/layout.tsx
  src/features/index.ts
  src/features/travel-schedule/index.ts
  src/features/travel-schedule/travel-schedule.model.ts
  src/features/travel-schedule/travel-schedule.slice.ts
  src/providers/TravelScheduleStoreProvider.tsx
  src/providers/index.ts
Labels: feature

#19 chore: create deploy-to-aws-ec2.yml
  .github/workflows/deploy-to-aws-ec2.yml
Labels: Deploy, Setting

#22 chore: update deploy-to-aws-ec2.yml
  .github/workflows/deploy-to-aws-ec2.yml
Labels: Deploy, Setting

#24 chore: update pm2 script in deploy-to-aws-ec2.yml
  .github/workflows/deploy-to-aws-ec2.yml
Labels: Deploy, Setting

#21 chore: change eslint configuration
  eslint.config.mjs
  package-lock.json
  package.json
  src/components/NavigationBar.tsx
  src/features/travel-schedule/travel-schedule.model.ts
  src/features/travel-schedule/travel-schedule.slice.ts
  src/providers/TravelScheduleStoreProvider.tsx
  tsconfig.json
Labels: Setting, Refactor

#18 feat: Implement traveler mode view
  public/Like.png
  public/location-pin.svg
  public/traveler-mode-add-button.svg
  public/traveler-mode-delete-button.svg
  public/traveler-write-record.svg
  src/__test__/travel-schedule-actions.test.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/pages/index.ts
  src/app/pages/travel-auto-page.tsx
  src/app/pages/travel-traveler-page.tsx
  src/app/travel/auto/page.tsx
  src/app/travel/traveler/page.tsx
  src/components/TravelComponent.tsx
  src/components/travel/ContentsCard.tsx
  src/components/travel/PurpleBackground.tsx
  src/components/travel/index.ts
  src/components/travel/traveler/TravelerActivitySelection.tsx
  src/components/travel/traveler/TravelerAddDays.tsx
  src/components/travel/traveler/TravelerHeaderText.tsx
  src/components/travel/traveler/TravelerMain.tsx
  src/components/travel/traveler/TravelerModeLogo.tsx
  src/components/travel/traveler/TravelerScheduleConfirm.tsx
  src/components/travel/traveler/TravelerTimeSelection.tsx
  src/components/travel/traveler/TravelerTravelArrange.tsx
  src/components/travel/traveler/TravelerTravelReview.tsx
  src/components/travel/traveler/index.ts
  src/features/travel-schedule/travel-schedule.model.ts
  src/features/travel-schedule/travel-schedule.slice.ts
Labels: Feature, UI/UX

#26 fix: apply changes
  eslint.config.mjs
  src/app/pages/travel-traveler-page.tsx
  src/components/travel/traveler/TravelerAddDays.tsx
  src/components/travel/traveler/TravelerScheduleConfirm.tsx
  src/components/travel/traveler/TravelerTravelArrange.tsx
  src/components/travel/traveler/TravelerTravelReview.tsx
Labels: Bug, Setting, Refactor

#29 feat: Added travel page
  public/chevron-bottom.svg
  public/moon-selected.svg
  public/moon.svg
  public/search-icon.svg
  public/sun-selected.svg
  public/sun.svg
  public/sunrise-selected.svg
  public/sunrise.svg
  public/sunset-selected.svg
  public/sunset.svg
  src/app/globals.css
  src/app/pages/index.ts
  src/app/pages/login-page.tsx
  src/app/pages/travel-auto-page.tsx
  src/app/pages/travel-page.tsx
  src/app/travel/page.tsx
  src/components/Background.tsx
  src/components/CustomButton.tsx
  src/components/Header.tsx
  src/components/ScrollMotion.tsx
  src/components/SearchBox.tsx
  src/components/TimeCard.tsx
  src/components/index.ts
  src/components/travel/ContentsCard.tsx
  src/features/travel-schedule/travel-schedule.type.ts
Labels: Feature, UI/UX

#33 fix: Issue with vertical scroll in traveler mode on mobile environment
  src/app/globals.css
  src/app/layout.tsx
Labels: Bug, Fix

#34 test: NavigationBar component UI test
  src/__test__/NavigationBar.test.tsx
Labels: Test

#39 chore: Add React Query
  .gitignore
  eslint.config.mjs
  package-lock.json
  package.json
  src/app/layout.tsx
  src/providers/TanStackQueryProvider.tsx
Labels: Setting
