Repository BTS-Busan-Trip-Supporter/front-end, pull requests merged in 2024-10, with the labels that each got.

#66 feat: apply feedback points
  src/app/pages/travel-traveler-page.tsx
  src/components/SearchBox.tsx
  src/components/travel/traveler/TravelerActivityRecommendation.tsx
  src/components/travel/traveler/TravelerAddDays.tsx
  src/components/travel/traveler/TravelerLocationSearch.tsx
  src/components/travel/traveler/TravelerScheduleConfirm.tsx
  src/components/travel/traveler/TravelerTravelArrange.tsx
  src/features/trip/trip.slice.ts
  src/providers/AuthProvider.tsx
Labels: Feature, API, UI/UX, Fix

#70 release: release v1.1.1 to main
  package-lock.json
  package.json
  src/components/profile/EditPasswordSection.tsx
  src/components/profile/EditProfileSection.tsx
  src/components/travel/traveler/TravelerScheduleConfirm.tsx
Labels: Deploy

#72 release: v1.1.2
  package-lock.json
  package.json
  src/components/profile/EditPasswordSection.tsx
Labels: Deploy, Release

#73 fix: Fixed password UI
  src/components/profile/EditPasswordSection.tsx
Labels: UI/UX

#74 release: v1.1.3
  package-lock.json
  package.json
  src/components/profile/EditPasswordSection.tsx
Labels: Deploy, UI/UX, Release

#75 release: v1.1.4
  package-lock.json
  package.json
  src/features/trip/trip.slice.ts
Labels: Bug, Deploy, Release, Fix
